# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: noreply@manyobra.com
  email_provider_password: noreplymanyobra
  domain_name: manyobra.com
  secret_key_base: 22c4ff70b9cb7a0bddd22b7998e06f34524f14eac269323903ba23f6b27df67cd2bb64989c4f0e162a8d317851c0fe6f87690ab2b0a67fa4ca22bc548bc390ac

test:
  secret_key_base: 6d10f124ab44ad4b55024bac434d857ac1335646486617259301f62e84e43cedd6e899ad11436d286ff17cbea26e3894257102c6357b4e4657879d50a4a21695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: noreply@manyobra.com
  email_provider_password: noreplymanyobra
  domain_name: manyobra.com
  secret_key_base: 6d10f124ab44ad4b55024bac434d857ac1335646486617259301f62e84e43cedd6e899ad11436d286ff17cbea26e3894257102c6357b4e4657879d50a4a21695
